# Generated by Django 3.1.4 on 2021-05-17 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mothersday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('img', models.ImageField(upload_to='pics')),
                ('price', models.IntegerField()),
                ('rate', models.IntegerField()),
            ],
            options={
                'db_table': 'mothersday',
            },
        ),
    ]
