# Generated by Django 3.1.4 on 2021-05-18 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_mothersday'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('story', models.CharField(max_length=500)),
                ('rate', models.IntegerField()),
            ],
            options={
                'db_table': 'reviews',
            },
        ),
    ]
