# Generated by Django 3.1.4 on 2021-05-18 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='ename',
            field=models.CharField(default=0, max_length=80),
            preserve_default=False,
        ),
    ]
