# Generated by Django 3.1.4 on 2021-05-18 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0004_review_ename'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='cam',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='ent',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='loc',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='nop',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='noti',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
