# Generated by Django 3.1.4 on 2021-05-18 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0006_auto_20210518_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='ent',
            field=models.CharField(max_length=10),
        ),
    ]
