# Generated by Django 3.1.4 on 2021-05-18 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0007_auto_20210518_1947'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('ename', models.CharField(max_length=80)),
                ('price', models.IntegerField()),
            ],
            options={
                'db_table': 'Billing',
            },
        ),
    ]
